### ISSUE TITLE
Why are you mixing the test suite and the Python implementation in the same project?

### ISSUE THREAD

**Issue by evanp** [w3c-social/activipy#1]
I thought we talked about having separate projects, so the same test suite could be used for multiple implementations (JS, Java, Python, Ruby, Scheme, etc.).

**Comment by cwebber** [comment]
Alright, well maybe they should be separate repositories.  What we had talked about involved a lot of flags involving pulling things out of activitystreams objects that something passes in.  It became hard for me to understand how to do this without it being an implementation.  The next step I was planning on adding was a validator which walks over an AS object and checks to see if it's right... I was planning on working in all the SHOULD parts as warnings and MUST parts of the AS2 spec as errors.  That way it could still extract fields in the ways you suggested but also handle the validation as part of the system.

My plan all along *was* to have the test suite with the command line interface you specified so it can be used by multiple projects.  You had also said on the last call that you'd like for Jessica and I to work on a project to make picking up AS2 easy.  I did my best to start moving towards that.

But if that's not good enough, maybe it should be a separate repository.  I'm okay with that... but I don't know how it should be structured at this point.  Can you help?

**Comment by cwebber** [comment]
Okay, having seen https://github.com/evanp/a2test I get what you were going for now.  That makes sense... a huge portion of my confusion was I thought you wanted the implementation to be calling the test scripts which were python, not the reverse... this is why I was so terribly confused.  So a2test makes sense, I get it now, let's go that direction.

Not all is lost though, I now realize that what I'm building here is an as2 validator, not a test suite... which is still valuable, but a different thing.  I'll rename the project appropriately.

**Comment by evanp** [comment]
There is probably huge value in a library that converts a chunk of JSON into Python class instances and then back to JSON. Putting that into PyPI would move things along a lot.
